apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-cm
data:
  cart_service_url: http://cart-service-svc.default.svc.cluster.local
  customer_profile_service_url: http://customer-profile-service-svc.default.svc.cluster.local
  order_service_url: http://order-service-svc.default.svc.cluster.local
  product_service_url: lb://product-service-svc.default.svc.cluster.local
  zipkin_service_url: http://zipkin-svc.default.svc.cluster.local:9411

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - name: api-gateway-app
          image: docker.io/jerrettg/grocery-e-commerce-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: product_service_url


---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-np
spec:
  selector:
    app: api-gateway-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
      nodePort: 30499

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
spec:
  selector:
    app: api-gateway-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP