package com.gonsalves.productservice.repository.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Objects;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Ecommerce-ProductService-Products")
public class ProductEntity {
    public static final String NAME_INDEX = "name-index";
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String productId;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = NAME_INDEX)
    @DynamoDBRangeKey(attributeName ="name")
    private String name;
    @DynamoDBAttribute(attributeName = "price")
    private Double price;
    @DynamoDBAttribute(attributeName = "unit_measurement")
    private String unitMeasurement;
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "category")
    private Category category;
    @DynamoDBAttribute(attributeName = "image_url")
    private String imageUrl;
    @DynamoDBAttribute(attributeName = "rating")
    private Double rating;
    @DynamoDBAttribute(attributeName = "listed_date")
    @DynamoDBAutoGeneratedTimestamp
    private String listedDate;

    public ProductEntity(String name, Double price, String description, Category category, String imageUrl, Double rating)
    {
        this.name = name;
        this.price = price;
        this.description = description;
        this.category = category;
        this.imageUrl = imageUrl;
        this.rating = rating;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ProductEntity productEntity = (ProductEntity) o;
        return productId == productEntity.productId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId);
    }

    @Override
    public String toString() {
        return "ProductEntity{"+
                "productId='" + productId + '\'' +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", unitMeasurement='" + unitMeasurement + '\'' +
                ", description='" + description + '\'' +
                ", category=" + category +
                ", imageUrl='" + imageUrl + '\'' +
                ", rating=" + rating +
                ", listedDate='" + listedDate + '\'' +
                '}';
    }
}
