version: '3.8'

services:
  discovery-service:
    container_name: discovery-service
    build:
      context: ./DiscoveryService
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  user-interface:
    container_name: user-interface
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka

  product-service:
    container_name: product-service
    build:
      context: ./Product-Service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}

  customer-profile-service:
    container_name: customer-profile-service
    build:
      context: ./CustomerProfile-Service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}

  cart-service:
    container_name: cart-service
    build:
      context: ./Cart-Service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
  order-service:
    container_name: order-service
    build:
      context: ./Order-Service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
  api-gateway:
    container_name: api-gateway
    build:
      context: ./Api-Gateway
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "9411:9411"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
