#server:
#  port: 8090
#
#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    loadbalancer:
#      kubernetes:
#        enabled: true
#    gateway:
#      routes:
#        - id: CART-SERVICE
#          uri: ${CART_SERVICE_URL}
#          predicates:
#            - Path=/api/***/cartService/**
#        - id: CUSTOMER-PROFILE-SERVICE
#          uri: ${CUSTOMER_PROFILE_SERVICE_URL}
#          predicates:
#              - Path=/api/***/customerProfileService/**
#        - id: ORDER-SERVICE
#          uri: ${ORDER_SERVICE_URL}
#          predicates:
#            - Path=/api/***/orderService/**
#        - id: PRODUCT-SERVICE
#          uri: ${PRODUCT_SERVICE_URL}
#          predicates:
#            - Path=/api/***/productService/**
#        - id: zipkin
#          uri: ${ZIPKIN_URL}
#          predicates:
#            - Path=/api/v2/spans

#spring:
#  application:
#    name: API-GATEWAY
#  cloud:
#    gateway:
#      routes:
#        - id: CART-SERVICE
#          uri: lb://CART-SERVICE
#          predicates:/api/***/cartService/**
#            - Path=
#        - id: CUSTOMER-PROFILE-SERVICE
#          uri: lb://CUSTOMER-PROFILE-SERVICE
#          predicates:
#            - Path=/api/***/customerProfileService/**
#        - id: ORDER-SERVICE
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/***/orderService/**
#        - id: PRODUCT-SERVICE
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#            - Path=/api/***/productService/**
#        - id: zipkin
#          uri: lb://ZIPKIN
#          predicates:
#            - Path=/api/v2/spans
#
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

