package com.gonsalves.customerprofileservice.repository.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Ecommerce-CustomerProfileService-Profiles")
public class CustomerProfileEntity {

    @DynamoDBHashKey(attributeName = "user_id")
    private String userId;
    @DynamoDBAttribute(attributeName = "email")
    private String email;
    @DynamoDBAttribute(attributeName = "first_name")
    private String firstName;
    @DynamoDBAttribute(attributeName = "last_name")
    private String lastName;
    @DynamoDBAttribute(attributeName = "shipping_address")
    private String shippingAddress;
    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "status")
    private Status status;
    @DynamoDBAttribute(attributeName = "creation_date")
    @DynamoDBAutoGeneratedTimestamp
    private String creationDate;
}
