package com.gonsalves.ProductService.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.xspec.S;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Objects;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Ecommerce-ProductService-Products")
public class Product {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String productId;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "name-index")
    @DynamoDBRangeKey(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "price")
    private double price;
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    @DynamoDBAttribute(attributeName = "category")
    private String category;
    @DynamoDBAttribute(attributeName = "image_url")
    private String imageUrl;
    @DynamoDBAttribute(attributeName = "rating")
    private double rating;
    @DynamoDBAttribute(attributeName = "listed_date")
    @DynamoDBAutoGeneratedTimestamp
    private String listedDate;

    public Product(String name, double price, String description, String category, String imageUrl, double rating)
    {
        this.name = name;
        this.price = price;
        this.description = description;
        this.category = category;
        this.imageUrl = imageUrl;
        this.rating = rating;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return productId == product.productId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId);
    }

    @Override
    public String toString() {
        return "Product{" +
                "productId='" + productId + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", category='" + category + '\'' +
                ", imageUrl='" + imageUrl + '\'' +
                ", rating=" + rating +
                ", listedDate='" + listedDate + '\'' +
                '}';
    }
}
