apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: docker.io/jerrettg/grocery-e-commerce-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8087
          env:
            - name: ZIPKIN_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: zipkin_service_url
            - name: GROCERY_AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: aws-region
            - name: GROCERY_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: aws-access-key-id
            - name: GROCERY_AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: aws-secret-key
---
kind: Service
apiVersion: v1
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
    - port: 80
      targetPort: 8087
