package com.gonsalves.orderservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Ecommerce-OrderService-Orders")
public class Order {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "user_id-index")
    @DynamoDBRangeKey(attributeName = "user_id")
    private String userId;
    @DynamoDBAttribute(attributeName = "shipping_address")
    private String shippingAddress;
    @DynamoDBAttribute(attributeName = "order_total")
    private double orderTotal;
    @DynamoDBAttribute(attributeName = "order_status")
    private String status;
    @DynamoDBAttribute(attributeName = "order_items")
    private List<OrderItem> orderItems;


}