#spring:
#  profiles:
#    default: default
#  application:
#    name: PRODUCT-SERVICE
#  zipkin:
#    base-url: ${ZIPKIN_SERVER_URL}
#
#
#dynamodb:
#  override_endpoint: false
#server:
#  port: 8081
#
#eureka:
#  instance:
#    hostName: localhost
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 20
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
