apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-app
  labels:
    app: stripe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stripe-app
  template:
    metadata:
      labels:
        app: stripe-app
    spec:
      containers:
        - name: stripe-app
          image: stripe/stripe-cli:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: stripe-api-key
          command: ["stripe"]
          args: ["listen", "--api-key", "${STRIPE_API_KEY}", "-f", "http://frontend-web-svc.default.svc.cluster.local/stripe/events"]
---
kind: Service
apiVersion: v1
metadata:
  name: stripe-svc
spec:
  selector:
    app: stripe-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8086
---
kind: Service
apiVersion: v1
metadata:
  name: stripe-np
spec:
  selector:
    app: stripe-app
  type: NodePort
  ports:
    - port: 80
      nodePort: 30497