apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe-deployment
  labels:
    app: stripe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stripe
  template:
    metadata:
      labels:
        app: stripe
    spec:
      containers:
        - name: stripe
          image: stripe/stripe-cli:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: stripe-api-key
          command: ["stripe"]
          args: ["listen", "--api-key", "${STRIPE_API_KEY}", "-f", "http://api-gateway-svc.grocery-dev.svc.cluster.local:8080/stripe/events"]
---
kind: Service
apiVersion: v1
metadata:
  name: stripe-svc
spec:
  selector:
    app: stripe
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8086