apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-app
  labels:
    app: zipkin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-app
  template:
    metadata:
      labels:
        app: zipkin-app
    spec:
      containers:
        - name: zipkin-app
          image: openzipkin/zipkin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9411
---
kind: Service
apiVersion: v1
metadata:
  name: zipkin-lb-svc
spec:
  selector:
    app: zipkin-app
  type: LoadBalancer
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30973

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
  labels:
    app: zipkin-app
spec:
  type: ClusterIP
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: zipkin-app