server:
  port: 8084

spring:
  application:
    name: USER-INTERFACE
  zipkin:
    base-url: http://127.0.0.1:9411/
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: dZfTEE09dqnnPQSj35bKeci6DWu0rvIx
            client-secret: 1GDdY0Txni9VerlG6LaLC3Shol4GxQdPmAzSKRJdPZj0hPbmOHr8QDVVnk3fVMu_
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-cd4uq5z8.us.auth0.com/
eureka:
  instance:
    hostname: discovery-service
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

stripe:
  public:
    key: ${STRIPE_PUBLIC_KEY}
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
