spring:
  application:
    name: 'USER_INTERFACE'
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: dZfTEE09dqnnPQSj35bKeci6DWu0rvIx
            client-secret: 1GDdY0Txni9VerlG6LaLC3Shol4GxQdPmAzSKRJdPZj0hPbmOHr8QDVVnk3fVMu_
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-cd4uq5z8.us.auth0.com/
stripe:
  public:
    key: pk_test_51Lpxs9CxL8dwOSYMcbunMozyxQMTuigezAbD8elm2KYijgm8IMqR2QhbPpgidYjdTTQdNsMQYXO0n6SGRvU8Xnnn00SCjK2c9v
  api:
    key: sk_test_51Lpxs9CxL8dwOSYMg2pPry1ijbuluheFO0PpUZSAWluirFCVHYc0yvJG0IQpN3qNQ6f3lV9f6ZvR8P0Vtgc2roo000RJ5BXpqm


server:
  port: 8084

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
