#server:
#  port: 8083
#
#
#spring:
#  application:
#    name: CART-SERVICE
#  zipkin:
#    base-url: ${ZIPKIN_SERVER_URL}

#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 20
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
