apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-profile-service-deployment
  labels:
    app: customer-profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-profile-service
  template:
    metadata:
      labels:
        app: customer-profile-service
    spec:
      containers:
        - name: customer-profile-service
          image: docker.io/jerrettg/grocery-e-commerce-customer-profile-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GROCERY_AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: aws-region
            - name: GROCERY_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: aws-access-key-id
            - name: GROCERY_AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: aws-secret-key
---
kind: Service
apiVersion: v1
metadata:
  name: customer-profile-service-svc
spec:
  selector:
    app: customer-profile-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP