apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface-app
  labels:
    app: user-interface-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-interface-app
  template:
    metadata:
      labels:
        app: user-interface-app
    spec:
      containers:
        - name: user-interface-app
          image: docker.io/jerrettg/grocery-e-commerce-user-interface:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: stripe-api-key
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: stripe-public-key
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: stripe-webhook-secret
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: auth-client-id
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: auth-client-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-interface-svc
  labels:
    app: user-interface
spec:
  selector:
    app: user-interface
  type: LoadBalancer
  ports:
    - port: 80
      targetPort:  8084
      protocol: TCP
---